spring.application.name=realnest-backend

# Disable local MongoDB
# spring.data.mongodb.uri=mongodb://localhost:27017/realnestdb

server.port=${PORT:8080}

spring.data.mongodb.uri=mongodb+srv://chouhanneha7150_db_user:nehachouhan2720@cluster0.etr29dd.mongodb.net/realnestdb?retryWrites=true&w=majority