spring.application.name=realnest-backend

# ? Disable local MongoDB (important for deployment)
# spring.data.mongodb.uri=mongodb://localhost:27017/realnestdb

# ? Required for Render (dynamic port)
server.port=${PORT}